// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemplateApp.Data;

namespace TemplateApp.Data.Migrations
{
    [DbContext(typeof(TemplateAppDbContext))]
    [Migration("20190518103810_UniqueClick2")]
    partial class UniqueClick2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TemplateApp.Data.Models.IpAdress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("IpAdresses");
                });

            modelBuilder.Entity("TemplateApp.Data.Models.PageStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("UniqueVisits");

                    b.Property<int>("Visits");

                    b.HasKey("Id");

                    b.ToTable("PageStatistics");
                });

            modelBuilder.Entity("TemplateApp.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClickCounter");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("ImageLink");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("TemplateApp.Data.Models.UniqueClick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClickCounter");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("IpAdressId");

                    b.Property<int>("IpAdressIp");

                    b.Property<int>("PostId");

                    b.HasKey("Id");

                    b.HasIndex("IpAdressId");

                    b.HasIndex("PostId");

                    b.ToTable("UniqueClicks");
                });

            modelBuilder.Entity("TemplateApp.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Token");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TemplateApp.Data.Models.UniqueClick", b =>
                {
                    b.HasOne("TemplateApp.Data.Models.IpAdress", "IpAdress")
                        .WithMany()
                        .HasForeignKey("IpAdressId");

                    b.HasOne("TemplateApp.Data.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
